# Generated by Django 6.0.7 on 2026-08-06 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documenetchunk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumenetChunk',
            new_name='DocumentChunk',
        ),
    ]
