# Generated by Django 6.0.7 on 2026-08-08 13:54

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_documenetchunk_documentchunk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentchunk',
            name='chunk_index',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='created_at',
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, null=True),
        ),
    ]
