# Generated by Django 6.0.7 on 2026-08-11 14:36

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_documentchunk_chunk_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
