# Generated by Django 6.0.7 on 2026-08-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documentchunk_chunk_index_documentchunk_page_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='chunk_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
